// generated by typst/gen-hosts from /home/mktips/pockt/bsh.nvim/examples/bsh-home/db/data/ — do not edit by hand
#let hosts = (
  "gate": (sys: "gate", ip: "192.168.1.1", dom: "gate.lan", ether: "00:11:22:33:44:01", vlan: "10", role: "router"),
  "gate.lan": (sys: "gate", ip: "192.168.1.1", dom: "gate.lan", ether: "00:11:22:33:44:01", vlan: "10", role: "router"),
  "server": (sys: "server", ip: "192.168.1.10", dom: "server.lan", ether: "00:11:22:33:44:02", role: "fileserver", service: "nfs"),
  "server.lan": (sys: "server", ip: "192.168.1.10", dom: "server.lan", ether: "00:11:22:33:44:02", role: "fileserver", service: "nfs"),
  "laptop": (sys: "laptop", ip: "192.168.1.20", dom: "laptop.lan", ether: "00:11:22:33:44:03", owner: "mara", os: "freebsd"),
  "laptop.lan": (sys: "laptop", ip: "192.168.1.20", dom: "laptop.lan", ether: "00:11:22:33:44:03", owner: "mara", os: "freebsd"),
  "phone": (sys: "phone", ip: "192.168.1.21", owner: "mara"),
  "printer": (sys: "printer", ip: "192.168.1.30", dom: "printer.lan", role: "printer", model: "hl-l2350dw"),
  "printer.lan": (sys: "printer", ip: "192.168.1.30", dom: "printer.lan", role: "printer", model: "hl-l2350dw"),
  "simurgh-base": (sys: "simurgh-base", dom: "simurgh-base", user: "mktips", os: "fedora", role: "desktop", loc: "home", note: "home-pc"),
  "mobile-base": (sys: "mobile-base", dom: "mobile-base", user: "mktips", os: "fedora", role: "laptop", loc: "mobile", note: "this-machine"),
  "university-base": (sys: "university-base", dom: "university-base", os: "freebsd", role: "server", loc: "university"),
  "mkti-ps": (sys: "mkti-ps", dom: "mkti-ps", fqdn: "mkti.ps", os: "freebsd", role: "server"),
  "mkti.ps": (sys: "mkti-ps", dom: "mkti-ps", fqdn: "mkti.ps", os: "freebsd", role: "server"),
)
